name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Disable Engines Check and Install
        run: npm install --legacy-peer-deps
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      - name: Build Web App
        run: npm run build

      - name: Capacitor Sync
        run: npx cap sync android

      - name: Build Android APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: nAPPo-Trails-Debug-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
